version: '3.9'
services:
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-0.14.6
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - voicevox_engine
    ports:
      - "${NGINX_HOST_PORT:?}:80"
    volumes:
      - ./volumes/nginx_secrets:/nginx_secrets
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
